### ISSUE TITLE
バグ:「解説」欄の文字列の1文字目に”,”を入れると再ロード後に後続の文字が表示されない

### ISSUE THREAD

**Issue by narihara-hakase** [hiryuushiva/SW_MonsterDataTool#3]
# 概要
画像のように「解説」欄の文字列の1文字目に”,”を入れると、データを再ロードした時に文字が表示されなくなる。
![image](https://user-images.githubusercontent.com/15346618/127762599-1f2fcd59-b592-4776-81a9-48f82607afa0.png)

# 原因推測
モンスターデータを保存しているcsvではこのように表示されていた。
> 解説,,testet

おそらく文字列がそのままcsvに保存され、再ロードの際に解釈に失敗しているのだと思われる。その他の文字列もそのままcsvの保存しているとすると、解釈に失敗してアプリケーションがエラー落ちすると予想できる(再現できなかったが、csvが原因でアプリが落ちたバグがあった。)

# 解決方針
文字列を保存する際にcsv上では文字列を表すリテラルで囲む。 例えばエクセルでは`"解説","testet"` と表記し、パースの際に`""`を消去している

**Comment by hiryuushiva** [comment]
今回のアップデートでおそらく修正できたと思います
