### ISSUE TITLE
要望::モンスターデーターの固定値自動入力機能

### ISSUE THREAD

**Issue by narihara-hakase** [hiryuushiva/SW_MonsterDataTool#4]
# モンスターデータを入力する際に自動的に固定値を入力したい！
モンスターデータを入力するときに基礎値を入力したら自動的に+7された値が`(n)`に入るような機能があったら便利だと思う
![image](https://user-images.githubusercontent.com/15346618/127762845-ebbc48e7-61d6-4869-9ae5-f7521a2a7dd0.png)

**Comment by hiryuushiva** [comment]
今回のアップデートで機能を追加しました
