### ISSUE TITLE
要望::他部位モンスターもユドナリウムのインベントリに表示したい。

### ISSUE THREAD

**Issue by narihara-hakase** [hiryuushiva/SW_MonsterDataTool#5]
# ユドナリウムで他部位モンスターでもインベントリ欄にライフを出せるようにしたい
[ここらへん](https://takahaltrpg.hatenablog.jp/entry/2020/01/28/%E3%83%A6%E3%83%89%E3%83%8A%E3%83%AA%E3%82%A6%E3%83%A0%E7%94%A8_%E3%82%A8%E3%83%8D%E3%83%9F%E3%83%BC%E3%83%87%E3%83%BC%E3%82%BF%E3%83%86%E3%83%B3%E3%83%97%E3%83%AC%E3%83%BC%E3%83%88)を参考にして、ユドナリウムのインベントリ欄にライフを出せるようにするか、部位ごとにモンスターコマを生成できるようにしたい

**Comment by hiryuushiva** [comment]
今まで通りのやり方のほかに個別の部位を出力できるようにしました
インベントリ欄のライフは個別に出した時HPと表示するようにして対応しました。
全ての部位で出力の方はシーンに合わせてインベントリに部位HPなどを追加してもらえればと思います
