### ISSUE TITLE
要望::ユドナ用チャットパレットの拡張

### ISSUE THREAD

**Issue by narihara-hakase** [hiryuushiva/SW_MonsterDataTool#6]
# ユドナリウム用あったら嬉しいチャパレ機能
以下のようなパレットが生成されたら嬉しい
- ダイスを振るリスト
    - ダメージ判定
    - 回避判定
    - 命中判定
    - 精神抵抗
    - 生命抵抗
    - 魔法判定
    - 特殊能力の判定 

- 固定値のリスト
    - ダメージ判定
    - 回避判定
    - 命中判定
    - 精神抵抗
    - 生命抵抗
    - 魔法判定
    - 特殊能力の判定

**Comment by hiryuushiva** [comment]
ダイスを振るリストと固定値のリスト別々に生成するようにしました
ダメージ、回避、命中、精神、生命は自動で生成するようにしましたが
魔法判定、特殊能力の各種判定は現在の記入方法では完全な自動生成は難しいと判断したので見送りました
かわりにチャットパレット編集機能を追加したのでそこで各自で記入してもらう形にしてみました
