### ISSUE TITLE
要望::データの編集機能を一元化する

### ISSUE THREAD

**Issue by narihara-hakase** [hiryuushiva/SW_MonsterDataTool#7]
# 右クリックメニューで編集操作ができるような機能を追加する
データ編集機能とデータベースの再読み込み機能の使い勝手が悪いため、1つのUIに合体できたら嬉しいです。

# 操作イメージ
![image](https://user-images.githubusercontent.com/15346618/127763334-7ec8531b-5c1d-446a-a1d7-d1455105d765.png)

**Comment by hiryuushiva** [comment]
ver1.2で実装しました
